/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ButtonChangeTheme: typeof import('./components/utils/ButtonChangeTheme.vue')['default']
    CardLoading: typeof import('./components/utils/CardLoading.vue')['default']
    FranchiseAutocomplete: typeof import('./components/utils/FranchiseAutocomplete.vue')['default']
    FranchiseCard: typeof import('./components/utils/FranchiseCard.vue')['default']
    FranchiseForm: typeof import('./components/franchises/FranchiseForm.vue')['default']
    FranchiseInfo: typeof import('./components/franchises/FranchiseInfo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageRender: typeof import('./components/utils/ImageRender.vue')['default']
    Loading: typeof import('./components/utils/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateFranchiseForm: typeof import('./components/franchises/UpdateFranchiseForm.vue')['default']
    UpdateWaifuForm: typeof import('./components/waifus/UpdateWaifuForm.vue')['default']
    WaifuCard: typeof import('./components/utils/WaifuCard.vue')['default']
    WaifuForm: typeof import('./components/waifus/WaifuForm.vue')['default']
    WaifuInfo: typeof import('./components/waifus/WaifuInfo.vue')['default']
    WaifuInfu: typeof import('./components/waifus/WaifuInfu.vue')['default']
  }
}
