/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CardLoading: typeof import('./components/CardLoading.vue')['default']
    FranchiseAutocomplete: typeof import('./components/FranchiseAutocomplete.vue')['default']
    FranchiseCard: typeof import('./components/FranchiseCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageRender: typeof import('./components/ImageRender.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateWaifuForm: typeof import('./components/waifus/UpdateWaifuForm.vue')['default']
    WaifuCard: typeof import('./components/WaifuCard.vue')['default']
    WaifuInfo: typeof import('./components/waifus/WaifuInfo.vue')['default']
    WaifuInfu: typeof import('./components/waifus/WaifuInfu.vue')['default']
  }
}
