/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/franchises/': RouteRecordInfo<'/franchises/', '/franchises', Record<never, never>, Record<never, never>>,
    '/franchises/:id': RouteRecordInfo<'/franchises/:id', '/franchises/:id', Record<never, never>, Record<never, never>>,
    '/franchises/new': RouteRecordInfo<'/franchises/new', '/franchises/new', Record<never, never>, Record<never, never>>,
    '/waifus/': RouteRecordInfo<'/waifus/', '/waifus', Record<never, never>, Record<never, never>>,
    '/waifus/:id': RouteRecordInfo<'/waifus/:id', '/waifus/:id', Record<never, never>, Record<never, never>>,
    '/waifus/new': RouteRecordInfo<'/waifus/new', '/waifus/new', Record<never, never>, Record<never, never>>,
  }
}
